package ummisco.genstar.gama;

public class PROPERTY_FILES {

	public static final class FREQUENCY_DISTRIBUTION_POPULATION_PROPERTIES {

		public static final String POPULATION_NAME_PROPERTY = "POPULATION_NAME";

		public static final String ATTRIBUTES_PROPERTY = "ATTRIBUTES";

		public static final String GENERATION_RULES_PROPERTY = "GENERATION_RULES";

		public static final String NUMBER_OF_ENTITIES = "NUMBER_OF_ENTITIES";
	}

	public static final class RANDOM_POPULATION_PROPERTIES {

		public static final String POPULATION_NAME_PROPERTY = "POPULATION_NAME";

		public static final String ATTRIBUTES_PROPERTY = "ATTRIBUTES";

		public static final String NB_OF_ENTITIES_PROPERTY = "NB_OF_ENTITIES";
	}

	public static final class RANDOM_COMPOUND_POPULATION_PROPERTIES {

		public static final String GROUP_POPULATION_NAME_PROPERTY = "GROUP_POPULATION_NAME";

		public static final String GROUP_ATTRIBUTES_PROPERTY = "GROUP_ATTRIBUTES";

		
		public static final String NB_OF_GROUP_ENTITIES_PROPERTY = "NB_OF_GROUP_ENTITIES";
		
		public static final String MIN_GROUP_ENTITIES_OF_EACH_ATTRIBUTE_VALUES_SET_PROPERTY = "MIN_GROUP_ENTITIES_OF_EACH_ATTRIBUTE_VALUES_SET";
		
		public static final String MAX_GROUP_ENTITIES_OF_EACH_ATTRIBUTE_VALUES_SET_PROPERTY = "MAX_GROUP_ENTITIES_OF_EACH_ATTRIBUTE_VALUES_SET";
		

		public static final String GROUP_SIZE_ATTRIBUTE_PROPERTY = "GROUP_SIZE_ATTRIBUTE";

		public static final String COMPONENT_POPULATION_NAME_PROPERTY = "COMPONENT_POPULATION_NAME";

		public static final String COMPONENT_ATTRIBUTES_PROPERTY = "COMPONENT_ATTRIBUTES";

		public static final String GROUP_ID_ATTRIBUTE_ON_GROUP_PROPERTY = "GROUP_ID_ATTRIBUTE_ON_GROUP";

		public static final String GROUP_ID_ATTRIBUTE_ON_COMPONENT_PROPERTY = "GROUP_ID_ATTRIBUTE_ON_COMPONENT";

		
		public static final String COMPONENT_REFERENCE_ON_GROUP_PROPERTY = "COMPONENT_REFERENCE_ON_GROUP";

		public static final String GROUP_REFERENCE_ON_COMPONENT_PROPERTY = "GROUP_REFERENCE_ON_COMPONENT";
	}

	public static final class CONTROL_TOTALS_PROPERTIES { // IPF_CONTROL_TOTALS_PROPERTIES ???

		public static final String ATTRIBUTES_PROPERTY = "ATTRIBUTES";

		public static final String ID_ATTRIBUTE_PROPERTY = "ID_ATTRIBUTE";

		public static final String CONTROLLED_ATTRIBUTES_PROPERTY = "CONTROLLED_ATTRIBUTES";

		public static final String POPULATION_DATA_PROPERTY = "POPULATION_DATA";
	}

	
	public static final class EXTRACT_IPU_POPULATION_PROPERTIES {

		// group population +
		public static final String GROUP_ATTRIBUTES_PROPERTY = "GROUP_ATTRIBUTES";

		public static final String GROUP_POPULATION_NAME_PROPERTY = "GROUP_POPULATION_NAME";

		public static final String GROUP_POPULATION_DATA_PROPERTY = "GROUP_POPULATION_DATA";

		public static final String GROUP_ID_ATTRIBUTE_ON_GROUP_PROPERTY = "GROUP_ID_ATTRIBUTE_ON_GROUP";
		
		public static final String GROUP_CONTROLLED_ATTRIBUTES_PROPERTY = "GROUP_CONTROLLED_ATTRIBUTES";
		// group population -

		
		// component population +
		public static final String COMPONENT_ATTRIBUTES_PROPERTY = "COMPONENT_ATTRIBUTES";

		public static final String COMPONENT_POPULATION_NAME_PROPERTY = "COMPONENT_POPULATION_NAME";

		public static final String COMPONENT_POPULATION_DATA_PROPERTY = "COMPONENT_POPULATION_DATA";

		public static final String GROUP_ID_ATTRIBUTE_ON_COMPONENT_PROPERTY = "GROUP_ID_ATTRIBUTE_ON_COMPONENT";
		// component population -
		
		
		// percentage
		public static final String PERCENTAGE_PROPERTY = "PERCENTAGE";
		

		public static final String COMPONENT_REFERENCE_ON_GROUP_PROPERTY = "COMPONENT_REFERENCE_ON_GROUP";

		public static final String GROUP_REFERENCE_ON_COMPONENT_PROPERTY = "GROUP_REFERENCE_ON_COMPONENT";
	}

	
	// TODO divide this class into two: IPF_POPULATION_PROPERTIES and COMPOUND_IPF_POPULATION_PROPERTIES ?
	public static final class IPF_POPULATION_PROPERTIES {

		public static final String POPULATION_NAME_PROPERTY = "POPULATION_NAME";

		public static final String ATTRIBUTES_PROPERTY = "ATTRIBUTES";

		public static final String SAMPLE_DATA_PROPERTY = "SAMPLE_DATA";

		public static final String CONTROLLED_ATTRIBUTES_PROPERTY = "CONTROLLED_ATTRIBUTES";

		public static final String CONTROL_TOTALS_PROPERTY = "CONTROL_TOTALS";

		public static final String SUPPLEMENTARY_ATTRIBUTES_PROPERTY = "SUPPLEMENTARY_ATTRIBUTES";

		public static final String MAX_ITERATIONS_PROPERTY = "MAX_ITERATIONS";

		// ATTENTION: if this property exists then the corresponding sample data is a compound sample data
		public static final String COMPONENT_POPULATION_NAME_PROPERTY = "COMPONENT_POPULATION_NAME";

		public static final String COMPONENT_SAMPLE_DATA_PROPERTY = "COMPONENT_SAMPLE_DATA";

		public static final String COMPONENT_ATTRIBUTES_PROPERTY = "COMPONENT_ATTRIBUTES";

		public static final String GROUP_ID_ATTRIBUTE_ON_GROUP_PROPERTY = "GROUP_ID_ATTRIBUTE_ON_GROUP";

		public static final String GROUP_ID_ATTRIBUTE_ON_COMPONENT_PROPERTY = "GROUP_ID_ATTRIBUTE_ON_COMPONENT";

		public static final String COMPONENT_REFERENCE_ON_GROUP_PROPERTY = "COMPONENT_REFERENCE_ON_GROUP";

		public static final String GROUP_REFERENCE_ON_COMPONENT_PROPERTY = "GROUP_REFERENCE_ON_COMPONENT";
	}
	

	public static final class IPU_POPULATION_PROPERTIES {

		// group population +
		public static final String GROUP_ATTRIBUTES_PROPERTY = "GROUP_ATTRIBUTES";

		public static final String GROUP_POPULATION_NAME_PROPERTY = "GROUP_POPULATION_NAME";

		public static final String GROUP_SAMPLE_DATA_PROPERTY = "GROUP_SAMPLE_DATA";

		public static final String GROUP_ID_ATTRIBUTE_ON_GROUP_PROPERTY = "GROUP_ID_ATTRIBUTE_ON_GROUP";

		public static final String GROUP_CONTROLLED_ATTRIBUTES_PROPERTY = "GROUP_CONTROLLED_ATTRIBUTES";

		public static final String GROUP_CONTROL_TOTALS_PROPERTY = "GROUP_CONTROL_TOTALS";

		public static final String GROUP_SUPPLEMENTARY_ATTRIBUTES_PROPERTY = "GROUP_SUPPLEMENTARY_ATTRIBUTES";
		// group population -
		

		// component population +
		public static final String COMPONENT_ATTRIBUTES_PROPERTY = "COMPONENT_ATTRIBUTES";

		public static final String COMPONENT_POPULATION_NAME_PROPERTY = "COMPONENT_POPULATION_NAME";

		public static final String COMPONENT_SAMPLE_DATA_PROPERTY = "COMPONENT_SAMPLE_DATA";

		public static final String GROUP_ID_ATTRIBUTE_ON_COMPONENT_PROPERTY = "GROUP_ID_ATTRIBUTE_ON_COMPONENT";

		public static final String COMPONENT_CONTROLLED_ATTRIBUTES_PROPERTY = "COMPONENT_CONTROLLED_ATTRIBUTES";

		public static final String COMPONENT_CONTROL_TOTALS_PROPERTY = "COMPONENT_CONTROL_TOTALS";

		public static final String COMPONENT_SUPPLEMENTARY_ATTRIBUTES_PROPERTY = "COMPONENT_SUPPLEMENTARY_ATTRIBUTES";
		// component population -
		

		public static final String COMPONENT_REFERENCE_ON_GROUP_PROPERTY = "COMPONENT_REFERENCE_ON_GROUP";

		public static final String GROUP_REFERENCE_ON_COMPONENT_PROPERTY = "GROUP_REFERENCE_ON_COMPONENT";

		public static final String MAX_ITERATIONS_PROPERTY = "MAX_ITERATIONS";

	}
	
	
	public static final class POPULATION_TO_CSV_PROPERTIES {
		
		public static final String ATTRIBUTES_PROPERTY = "ATTRIBUTES";

		public static final String OUTPUT_FILE_PROPERTY = "OUTPUT_FILE";
	}
	
	
	public static final class COMPOUND_POPULATION_TO_CSV_PROPERTIES {
		
		public static final String GROUP_ATTRIBUTES_PROPERTY = "GROUP_ATTRIBUTES";
		
		public static final String GROUP_OUTPUT_FILE_PROPERTY = "GROUP_OUTPUT_FILE";
		
		public static final String COMPONENT_ATTRIBUTES_PROPERTY = "COMPONENT_ATTRIBUTES";
		
		public static final String COMPONENT_OUTPUT_FILE_PROPERTY = "COMPONENT_OUTPUT_FILE";
	}
	
	
	public static final class LOAD_POPULATION_PROPERTIES {
		
		public static final String POPULATION_NAME_PROPERTY = "POPULATION_NAME";

		public static final String ATTRIBUTES_PROPERTY = "ATTRIBUTES";

		public static final String POPULATION_DATA_PROPERTY = "POPULATION_DATA";
	}
	
	
	public static final class LOAD_COMPOUND_POPULATION_PROPERTIES {
		
		public static final String GROUP_POPULATION_NAME_PROPERTY = "GROUP_POPULATION_NAME";

		public static final String GROUP_ATTRIBUTES_PROPERTY = "GROUP_ATTRIBUTES";

		public static final String GROUP_POPULATION_DATA_PROPERTY = "GROUP_POPULATION_DATA";
		

		public static final String COMPONENT_POPULATION_NAME_PROPERTY = "COMPONENT_POPULATION_NAME";

		public static final String COMPONENT_ATTRIBUTES_PROPERTY = "COMPONENT_ATTRIBUTES";

		public static final String COMPONENT_POPULATION_DATA_PROPERTY = "COMPONENT_POPULATION_DATA";

	
		public static final String GROUP_ID_ATTRIBUTE_ON_GROUP_PROPERTY = "GROUP_ID_ATTRIBUTE_ON_GROUP";

		public static final String GROUP_ID_ATTRIBUTE_ON_COMPONENT_PROPERTY = "GROUP_ID_ATTRIBUTE_ON_COMPONENT";

		
		public static final String COMPONENT_REFERENCE_ON_GROUP_PROPERTY = "COMPONENT_REFERENCE_ON_GROUP";

		public static final String GROUP_REFERENCE_ON_COMPONENT_PROPERTY = "GROUP_REFERENCE_ON_COMPONENT";
	}
}
