DROP TABLE ATTRIBUTE_INFERENCE_GENERATION_RULE;
DROP TABLE OUTPUT_ATTRIBUTE;
DROP TABLE INPUT_ATTRIBUTE;
DROP TABLE FREQUENCY_DISTRIBUTION_GENERATION_RULE;
DROP TABLE GENERATION_RULE;
DROP TABLE INFERENCE_RANGE_ATTRIBUTE_DATA2;
DROP TABLE INFERENCE_RANGE_ATTRIBUTE_DATA1;
DROP TABLE INFERENCE_VALUE_ATTRIBUTE_DATA2;
DROP TABLE INFERENCE_VALUE_ATTRIBUTE_DATA1;
DROP TABLE RANGE_VALUE;
DROP TABLE UNIQUE_VALUE;
DROP TABLE INFERRED_ATTRIBUTE;
DROP TABLE ENUMERATION_VALUE_ATTRIBUTE;
DROP TABLE ATTRIBUTE;
DROP TABLE ENTITY_ATTRIBUTE_RANGE_VALUE;
DROP TABLE ENTITY_ATTRIBUTE_UNIQUE_VALUE;
DROP TABLE ENTITY_ATTRIBUTE;
DROP TABLE ENTITY;
DROP TABLE SYNTHETIC_POPULATION;
DROP TABLE POPULATION_GENERATOR;
CREATE TABLE POPULATION_GENERATOR (
	POPULATION_GENERATOR_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL UNIQUE,
	INITIAL_NUMBER_OF_ENTITIES INT NOT NULL,
	CONSTRAINT INITIAL_NUMBER_OF_ENTITIES_CK CHECK (INITIAL_NUMBER_OF_ENTITIES > 0)
);
CREATE TABLE SYNTHETIC_POPULATION (
	POPULATION_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL UNIQUE,
	NUMBER_OF_ENTITIES INT NOT NULL
);
CREATE TABLE ENTITY (
	ENTITY_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	POPULATION_ID INT NOT NULL,
	CONSTRAINT SYNTHETIC_POPULATION_PK FOREIGN KEY (POPULATION_ID) REFERENCES SYNTHETIC_POPULATION(POPULATION_ID) ON DELETE CASCADE	
);
CREATE TABLE ENTITY_ATTRIBUTE (
	ENTITY_ATTRIBUTE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ENTITY_ID INT NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	TYPE SMALLINT NOT NULL,
	VALUE_TYPE SMALLINT NOT NULL,
	CONSTRAINT ENTITY_ID_PK FOREIGN KEY (ENTITY_ID) REFERENCES ENTITY(ENTITY_ID) ON DELETE CASCADE	
);
CREATE TABLE ENTITY_ATTRIBUTE_UNIQUE_VALUE (
	ENTITY_ATTRIBUTE_UNIQUE_VALUE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ENTITY_ATTRIBUTE_ID INT NOT NULL,
	STRING_VALUE VARCHAR(100) NOT NULL,
	CONSTRAINT ENTITY_ATTRIBUTE_ID_PK_1 FOREIGN KEY (ENTITY_ATTRIBUTE_ID) REFERENCES ENTITY_ATTRIBUTE(ENTITY_ATTRIBUTE_ID) ON DELETE CASCADE	
);
CREATE TABLE ENTITY_ATTRIBUTE_RANGE_VALUE (
	ENTITY_ATTRIBUTE_RANGE_VALUE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ENTITY_ATTRIBUTE_ID INT NOT NULL,
	MIN_STRING_VALUE VARCHAR(100) NOT NULL,
	MAX_STRING_VALUE VARCHAR(100) NOT NULL,
	CONSTRAINT ENTITY_ATTRIBUTE_ID_PK_2 FOREIGN KEY (ENTITY_ATTRIBUTE_ID) REFERENCES ENTITY_ATTRIBUTE(ENTITY_ATTRIBUTE_ID) ON DELETE CASCADE	
);
CREATE TABLE ATTRIBUTE (
	ATTRIBUTE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	POPULATION_GENERATOR_ID INT NOT NULL,
	NAME_ON_DATA VARCHAR(100) NOT NULL,
	NAME_ON_ENTITY VARCHAR(100) NOT NULL,
	VALUE_TYPE_ID SMALLINT NOT NULL,
	VALUE_CLASS_ON_DATA VARCHAR(100) NOT NULL,
	VALUE_CLASS_ON_ENTITY VARCHAR(100) NOT NULL,
	CONSTRAINT POPULATION_GENERATION_ID_PK FOREIGN KEY (POPULATION_GENERATOR_ID) REFERENCES POPULATION_GENERATOR(POPULATION_GENERATOR_ID) ON DELETE CASCADE		
);
CREATE TABLE ENUMERATION_VALUE_ATTRIBUTE (
	ENUMERATION_VALUE_ATTRIBUTE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ATTRIBUTE_ID INT NOT NULL,
	CONSTRAINT ATTRIBUTE_ID_FK1 FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ATTRIBUTE(ATTRIBUTE_ID) ON DELETE CASCADE		
);
CREATE TABLE INFERRED_ATTRIBUTE (
	INFERRED_ATTRIBUTE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ATTRIBUTE_ID INT NOT NULL,
	INFERRING_ATTRIBUTE_ID INT NOT NULL,
	CONSTRAINT ATTRIBUTE_ID_FK2 FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ATTRIBUTE(ATTRIBUTE_ID) ON DELETE CASCADE,		
	CONSTRAINT INFERRING_ATTRIBUTE_ID_PK1 FOREIGN KEY (INFERRING_ATTRIBUTE_ID) REFERENCES ATTRIBUTE(ATTRIBUTE_ID) ON DELETE CASCADE		
);
CREATE TABLE UNIQUE_VALUE (
	UNIQUE_VALUE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ATTRIBUTE_ID INT NOT NULL,
	STRING_VALUE VARCHAR(100) NOT NULL,
	CONSTRAINT ATTRIBUTE_ID_FK3 FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ATTRIBUTE(ATTRIBUTE_ID) ON DELETE CASCADE	
);
CREATE TABLE RANGE_VALUE (
	RANGE_VALUE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ATTRIBUTE_ID INT NOT NULL,
	MIN_STRING_VALUE VARCHAR(100) NOT NULL,
	MAX_STRING_VALUE VARCHAR(100) NOT NULL,
	CONSTRAINT ATTRIBUTE_ID_FK4 FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ATTRIBUTE(ATTRIBUTE_ID) ON DELETE CASCADE	
);
CREATE TABLE INFERENCE_VALUE_ATTRIBUTE_DATA1 (
	INFERENCE_VALUE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	INFERRED_ATTRIBUTE_ID INT NOT NULL,
	INFERRING_UNIQUE_VALUE_ID INT NOT NULL,
	INFERRED_UNIQUE_VALUE_ID INT NOT NULL,
	CONSTRAINT INFERRED_ATTRIBUTE_ID_FK1 FOREIGN KEY (INFERRED_ATTRIBUTE_ID) REFERENCES INFERRED_ATTRIBUTE(INFERRED_ATTRIBUTE_ID) ON DELETE CASCADE,
	CONSTRAINT INFERRING_UNIQUE_VALUE_ID_FK1 FOREIGN KEY (INFERRING_UNIQUE_VALUE_ID) REFERENCES UNIQUE_VALUE(UNIQUE_VALUE_ID) ON DELETE CASCADE,
	CONSTRAINT INFERRED_UNIQUE_VALUE_ID_FK1 FOREIGN KEY (INFERRED_UNIQUE_VALUE_ID) REFERENCES UNIQUE_VALUE(UNIQUE_VALUE_ID) ON DELETE CASCADE
);
CREATE TABLE INFERENCE_VALUE_ATTRIBUTE_DATA2 (
	INFERENCE_VALUE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	INFERRED_ATTRIBUTE_ID INT NOT NULL,
	INFERRING_RANGE_VALUE_ID INT NOT NULL,
	INFERRED_UNIQUE_VALUE_ID INT NOT NULL,	
	CONSTRAINT INFERRED_ATTRIBUTE_ID_FK2 FOREIGN KEY (INFERRED_ATTRIBUTE_ID) REFERENCES INFERRED_ATTRIBUTE(INFERRED_ATTRIBUTE_ID) ON DELETE CASCADE,
	CONSTRAINT INFERRING_RANGE_VALUE_ID_FK1 FOREIGN KEY (INFERRING_RANGE_VALUE_ID) REFERENCES RANGE_VALUE(RANGE_VALUE_ID) ON DELETE CASCADE,
	CONSTRAINT INFERRED_UNIQUE_VALUE_ID_FK2 FOREIGN KEY (INFERRED_UNIQUE_VALUE_ID) REFERENCES UNIQUE_VALUE(UNIQUE_VALUE_ID) ON DELETE CASCADE
);
CREATE TABLE INFERENCE_RANGE_ATTRIBUTE_DATA1 (
	INFERENCE_RANGE_ATTRIBUTE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	INFERRED_ATTRIBUTE_ID INT NOT NULL,
	INFERRING_UNIQUE_VALUE_ID INT NOT NULL,
	INFERRED_RANGE_VALUE_ID INT NOT NULL,	
	CONSTRAINT INFERRED_ATTRIBUTE_ID_FK3 FOREIGN KEY (INFERRED_ATTRIBUTE_ID) REFERENCES INFERRED_ATTRIBUTE(INFERRED_ATTRIBUTE_ID) ON DELETE CASCADE,
	CONSTRAINT INFERRING_UNIQUE_VALUE_ID_FK2 FOREIGN KEY (INFERRING_UNIQUE_VALUE_ID) REFERENCES UNIQUE_VALUE(UNIQUE_VALUE_ID) ON DELETE CASCADE,
	CONSTRAINT INFERRED_RANGE_VALUE_ID_FK1 FOREIGN KEY (INFERRED_RANGE_VALUE_ID) REFERENCES RANGE_VALUE(RANGE_VALUE_ID) ON DELETE CASCADE
);
CREATE TABLE INFERENCE_RANGE_ATTRIBUTE_DATA2 (
	INFERENCE_RANGE_ATTRIBUTE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	INFERRED_ATTRIBUTE_ID INT NOT NULL,
	INFERRING_RANGE_VALUE_ID INT NOT NULL,
	INFERRED_RANGE_VALUE_ID INT NOT NULL,
	CONSTRAINT INFERRED_ATTRIBUTE_ID_FK4 FOREIGN KEY (INFERRED_ATTRIBUTE_ID) REFERENCES INFERRED_ATTRIBUTE(INFERRED_ATTRIBUTE_ID) ON DELETE CASCADE,
	CONSTRAINT INFERRING_RANGE_VALUE_ID_FK2 FOREIGN KEY (INFERRING_RANGE_VALUE_ID) REFERENCES RANGE_VALUE(RANGE_VALUE_ID) ON DELETE CASCADE,
	CONSTRAINT INFERRED_RANGE_VALUE_ID_FK2 FOREIGN KEY (INFERRED_RANGE_VALUE_ID) REFERENCES RANGE_VALUE(RANGE_VALUE_ID) ON DELETE CASCADE
);
CREATE TABLE GENERATION_RULE (
	GENERATION_RULE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	POPULATION_GENERATOR_ID INT NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	RULE_ORDER INT NOT NULL,
	CONSTRAINT POPULATION_GENERATOR_ID_FK1 FOREIGN KEY (POPULATION_GENERATOR_ID) REFERENCES POPULATION_GENERATOR(POPULATION_GENERATOR_ID) ON DELETE CASCADE,
	CONSTRAINT RULE_ORDER_CK CHECK (RULE_ORDER >= 1)
);
CREATE TABLE FREQUENCY_DISTRIBUTION_GENERATION_RULE (
	FREQUENCY_DISTRIBUTION_GENERATION_RULE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	GENERATION_RULE_ID INT NOT NULL,
	CONSTRAINT GENERATION_RULE_ID_FK1 FOREIGN KEY (GENERATION_RULE_ID) REFERENCES GENERATION_RULE(GENERATION_RULE_ID) ON DELETE CASCADE
);
CREATE TABLE INPUT_ATTRIBUTE (
	INPUT_ATTRIBUTE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ENUMERATION_VALUE_ATTRIBUTE_ID INT NOT NULL,
	FREQUENCY_DISTRIBUTION_GENERATION_RULE_ID INT NOT NULL,
	ATTRIBUTE_ORDER INT NOT NULL,
	CONSTRAINT ENUMERATION_VALUE_ATTRIBUTE_ID_FK1 FOREIGN KEY (ENUMERATION_VALUE_ATTRIBUTE_ID) REFERENCES ENUMERATION_VALUE_ATTRIBUTE(ENUMERATION_VALUE_ATTRIBUTE_ID) ON DELETE CASCADE,
	CONSTRAINT FREQUENCY_DISTRIBUTION_GENERATION_RULE_ID_FK1 FOREIGN KEY (FREQUENCY_DISTRIBUTION_GENERATION_RULE_ID) REFERENCES FREQUENCY_DISTRIBUTION_GENERATION_RULE(FREQUENCY_DISTRIBUTION_GENERATION_RULE_ID) ON DELETE CASCADE,
	CONSTRAINT ATTRIBUTE_ORDER_CK1 CHECK (ATTRIBUTE_ORDER >= 1)
);
CREATE TABLE OUTPUT_ATTRIBUTE (
	OUTPUT_ATTRIBUTE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ENUMERATION_VALUE_ATTRIBUTE_ID INT NOT NULL,
	FREQUENCY_DISTRIBUTION_GENERATION_RULE_ID INT NOT NULL,
	ATTRIBUTE_ORDER INT NOT NULL,
	CONSTRAINT ENUMERATION_VALUE_ATTRIBUTE_ID_FK2 FOREIGN KEY (ENUMERATION_VALUE_ATTRIBUTE_ID) REFERENCES ENUMERATION_VALUE_ATTRIBUTE(ENUMERATION_VALUE_ATTRIBUTE_ID) ON DELETE CASCADE,
	CONSTRAINT FREQUENCY_DISTRIBUTION_GENERATION_RULE_ID_FK2 FOREIGN KEY (FREQUENCY_DISTRIBUTION_GENERATION_RULE_ID) REFERENCES FREQUENCY_DISTRIBUTION_GENERATION_RULE(FREQUENCY_DISTRIBUTION_GENERATION_RULE_ID) ON DELETE CASCADE,
	CONSTRAINT ATTRIBUTE_ORDER_CK2 CHECK (ATTRIBUTE_ORDER >= 1)
);
CREATE TABLE ATTRIBUTE_INFERENCE_GENERATION_RULE (
	ATTRIBUTE_INFERENCE_GENERATION_RULE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	GENERATION_RULE_ID INT NOT NULL,
	INFERRED_ATTRIBUTE_ID INT NOT NULL,
	CONSTRAINT GENERATION_RULE_ID_FK2 FOREIGN KEY (GENERATION_RULE_ID) REFERENCES GENERATION_RULE(GENERATION_RULE_ID) ON DELETE CASCADE,
	CONSTRAINT INFERRED_ATTRIBUTE_ID_FK5 FOREIGN KEY (INFERRED_ATTRIBUTE_ID) REFERENCES INFERRED_ATTRIBUTE(INFERRED_ATTRIBUTE_ID) ON DELETE CASCADE
);

